# Generated by Django 4.2 on 2023-04-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_description_long_alter_placeimage_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
    ]
