# Generated by Django 4.2 on 2023-04-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
