# Generated by Django 4.2 on 2023-04-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Поставь галочку, если нужно опубликовать место.', verbose_name='Опубликовано'),
        ),
    ]
